_format_version: "3.0"
_transform: true

services:
  - name: identity
    url: http://identity:8000
    routes:
      - name: identity-route
        paths: ["/identity"]
        strip_path: true
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp", "aud", "iss"]
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false
              header_names: ["Authorization"]
              uri_param_names: ["jwt"]
              
  - name: registry
    url: http://registry:8000
    routes:
      - name: registry-route
        paths: ["/registry"]
        strip_path: true
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp", "aud", "iss"]
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false
              header_names: ["Authorization"]
              
  - name: eligibility
    url: http://eligibility:8000
    routes:
      - name: eligibility-route
        paths: ["/eligibility"]
        strip_path: true
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp", "aud", "iss"]
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false
              header_names: ["Authorization"]
              
  - name: payment
    url: http://payment:8000
    routes:
      - name: payment-route
        paths: ["/payment"]
        strip_path: true
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp", "aud", "iss"]
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false
              header_names: ["Authorization"]
              
  - name: analytics
    url: http://analytics:8000
    routes:
      - name: analytics-route
        paths: ["/analytics"]
        strip_path: true
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp", "aud", "iss"]
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false
              header_names: ["Authorization"]

# Global plugins
plugins:
  - name: cors
    config:
      origins: ["${CORS_ALLOW_ORIGINS}"]
      methods: ["GET","POST","PUT","DELETE","OPTIONS"]
      headers: ["Authorization","Content-Type","X-Trace-Id"]
      exposed_headers: ["X-Trace-Id"]
      credentials: true
      max_age: 3600
      
  - name: rate-limiting
    config:
      minute: 6000
      hour: 100000
      policy: redis
      redis_host: redis
      redis_port: 6379
      fault_tolerant: true
      hide_client_headers: false
      
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      
  - name: bot-detection
    config:
      allow: []
      deny: []
      
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true

# JWT consumers for service-to-service communication
consumers:
  - username: dsrs-system
    jwt_secrets:
      - key: "https://auth.dsrs.example/realms/dsrs"
        algorithm: "RS256"
        rsa_public_key: "${JWT_PUBLIC_KEY}"
