_format_version: "3.0"
_transform: true
services:
  - name: registry
    url: http://registry:8000
    routes:
      - name: registry-route
        paths: [/api/v1/households]
        strip_path: false
plugins:
  - name: jwt
  - name: rate-limiting
    config:
      minute: 1000

