apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/identity-deployment.yaml
  - ../../k8s/registry-deployment.yaml
  - ../../k8s/eligibility-deployment.yaml
  - ../../k8s/payment-deployment.yaml
  - ../../k8s/analytics-deployment.yaml
  - ../../k8s/otel-collector.yaml
  - ../../k8s/dlq-reprocessor-deployment.yaml
  - ../../k8s/grafana.yaml
configMapGenerator:
  - name: dsrs-config
    literals:
      - ENVIRONMENT=production
      - CORS_ALLOW_ORIGINS=https://dsrs.example
      - LOG_JSON=1
      - OTEL_ENABLE=1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - ISSUER=https://auth.dsrs.example/realms/dsrs
      - AUDIENCE=dsrs-api
      # NOTE: ALLOW_INSECURE_LOCAL is NOT set - JWT enforcement is mandatory in production
secretGenerator:
  - name: dsrs-secrets
    literals:
      - registry_db_url=postgresql+psycopg://<set-in-secret>:<set-in-secret>@postgres:5432/registry
      - payment_db_url=postgresql+psycopg://<set-in-secret>:<set-in-secret>@postgres:5432/payment
      - analytics_mongo_url=mongodb://mongo:27017
generatorOptions:
  disableNameSuffixHash: true

