apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eligibility
  template:
    metadata:
      labels:
        app: eligibility
    spec:
      containers:
        - name: eligibility
          image: ghcr.io/your-org/eligibility:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: ISSUER
              valueFrom:
                configMapKeyRef:
                  name: dsrs-config
                  key: ISSUER
            - name: AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: dsrs-config
                  key: AUDIENCE
            - name: CORS_ALLOW_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: dsrs-config
                  key: CORS_ALLOW_ORIGINS
            - name: LOG_JSON
              valueFrom:
                configMapKeyRef:
                  name: dsrs-config
                  key: LOG_JSON
            - name: OTEL_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: dsrs-config
                  key: OTEL_ENABLE
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: dsrs-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: eligibility
spec:
  selector:
    app: eligibility
  ports:
    - port: 80
      targetPort: 8000

