apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: ghcr.io/your-org/identity:latest
          ports:
            - containerPort: 8000
          env:
            - name: ISSUER
              value: https://auth.yourdomain/realms/dsrs
            - name: AUDIENCE
              value: dsrs-api
---
apiVersion: v1
kind: Service
metadata:
  name: identity
spec:
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 8000

