livenessProbe:
  httpGet:
    path: /healthz/liveness
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz/readiness
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10

