apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: ghcr.io/your-org/registry:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dsrs-secrets
                  key: registry_db_url
            - name: ISSUER
              value: https://auth.yourdomain/realms/dsrs
            - name: AUDIENCE
              value: dsrs-api
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - port: 80
      targetPort: 8000

