apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/identity-deployment.yaml
  - ../../k8s/registry-deployment.yaml
  - ../../k8s/eligibility-deployment.yaml
  - ../../k8s/payment-deployment.yaml
  - ../../k8s/analytics-deployment.yaml
configMapGenerator:
  - name: dsrs-config
    literals:
      - ENVIRONMENT=development
      - CORS_ALLOW_ORIGINS=http://localhost:3000
      - LOG_JSON=0
      - OTEL_ENABLE=0
      - ISSUER=http://localhost:8080/realms/dsrs
      - AUDIENCE=dsrs-api
      - ALLOW_INSECURE_LOCAL=1  # Development bypass allowed
secretGenerator:
  - name: dsrs-secrets
    literals:
      - registry_db_url=postgresql+psycopg://dsrs:dsrs@postgres:5432/dsrs
      - payment_db_url=postgresql+psycopg://dsrs:dsrs@postgres:5432/dsrs
      - analytics_mongo_url=mongodb://mongo:27017
generatorOptions:
  disableNameSuffixHash: true

