apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/identity-deployment.yaml
  - ../../k8s/registry-deployment.yaml
  - ../../k8s/eligibility-deployment.yaml
  - ../../k8s/payment-deployment.yaml
  - ../../k8s/analytics-deployment.yaml
  - ../../k8s/otel-collector.yaml
  - ../../k8s/dlq-reprocessor-deployment.yaml
  - ../../k8s/grafana.yaml
  - ../../k8s/networkpolicies/00-default-deny.yaml
  - ../../k8s/networkpolicies/10-allow-kong-to-services.yaml
  - ../../k8s/networkpolicies/20-allow-services-egress.yaml
  - ../../k8s/networkpolicies/30-allow-prometheus-scrape.yaml
  - ../../k8s/hpa/registry-hpa.yaml
  - ../../k8s/hpa/eligibility-hpa.yaml
  - ../../k8s/hpa/payment-hpa.yaml
  - ../../k8s/hpa/analytics-hpa.yaml
  - ../../k8s/pdb/registry-pdb.yaml
  - ../../k8s/pdb/eligibility-pdb.yaml
  - ../../k8s/pdb/payment-pdb.yaml
  - ../../k8s/pdb/analytics-pdb.yaml
  - external-secrets.yaml
configMapGenerator:
  - name: dsrs-config
    literals:
      - ENVIRONMENT=staging
      - CORS_ALLOW_ORIGINS=https://staging.dsrs.example
      - LOG_JSON=1
      - OTEL_ENABLE=1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - ISSUER=https://auth.staging.example/realms/dsrs
      - AUDIENCE=dsrs-api
      - KAFKA_BROKERS=dsrs-kafka-kafka-bootstrap:9092
      # NOTE: ALLOW_INSECURE_LOCAL is NOT set - JWT enforcement is mandatory in staging
# External Secrets replaces secretGenerator
# secretGenerator:
#   - name: dsrs-secrets
#     literals:
#       - registry_db_url=...
#       - payment_db_url=...
#       - analytics_mongo_url=...
generatorOptions:
  disableNameSuffixHash: true

