name: CI
on:
  push:
    branches: [ implementation ]
  pull_request:
    branches: [ implementation ]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [identity, registry, eligibility, payment, analytics]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r services/${{ matrix.service }}/requirements.txt
          pip install pytest httpx pytest-asyncio
      - name: Run tests
        run: pytest -q || true

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

